name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: ['**']

jobs:
  test:
    name: Run linter and tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 22.x, 24.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: yarn install

    - name: Run linter and tests
      run: |
        yarn lint
        yarn test
        yarn coverage

    - name: Send test coverage report to Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
